# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_album_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='detailed_description',
            field=models.CharField(default=b'detailed desc', max_length=50),
        ),
        migrations.AddField(
            model_name='album',
            name='online_description',
            field=models.CharField(default=b'online desc', max_length=50),
        ),
        migrations.AddField(
            model_name='album',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='album',
            name='release_date',
            field=models.CharField(default=b'01-04-2017', max_length=30),
        ),
        migrations.AddField(
            model_name='album',
            name='support_platform',
            field=models.CharField(default=b'Windows', max_length=30),
        ),
    ]
